pub mod get;
pub mod get_results;
pub mod get_candidates_by_country;
pub mod get_results_by_country;
pub mod get_landslide_victory;
pub mod get_top_five_candidates_by_vote;
pub mod get_closest_vote_difference;
pub mod post_vote;
pub mod post;